-- Vacia a proposito. Agregaba `agentes.bot` (de que bot era cada cuenta de
-- Claude: punchi, homero o patan); la 046 la saca porque las cuentas volvieron
-- a ser un fondo comun que usa solo el gateway.
--
-- No se borra el archivo para que el numero no se reuse, y no se deja como
-- estaba porque las migraciones corren todas en cada arranque: la 038 la
-- volveria a crear y la 046 la volveria a borrar, una vez por arranque.
